name: fontawesome_elements
version: 0.0.2
author: Adam J. Cook <adam.joseph.cook@gmail.com>
description: Polymer icon elements featuring Font Awesome.
homepage: https://github.com/adamjcook/fontawesome-elements
dependencies:
  polymer: '>=0.11.0+1 <0.12.0'
  quiver: '>=0.17.0 <0.19.0'
  web_components: '>=0.4.0 <0.5.0'
dev_dependencies:
  html5lib: '>=0.11.0 <0.12.0'
  path: '>=1.0.0 <2.0.0'
  yaml: '>=1.0.0 <2.0.0'
transformers:
- polymer:
    entry_points:
    - example/fontawesome_icon_button.html
    - example/fontawesome_icon_svg.html
    lint: false